name: PR Review

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "dev"

jobs:
  review:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: "Install Dependencies"
        run: |
          yarn

      - name: "Lint Check"
        run: yarn lint

      - name: "Build Check"
        run: yarn build

      - name: "Fix yarn issue temporarily"
        run: |
          rm ./todo-list-app/yarn.lock
          rm ./todo-list-rest-server/yarn.lock
          yarn

      - name: 'Setup test .env'
        run: |
          cd todo-list-rest-server
          cat .env.template
          sed -i "s/{{ENV}}/development/g" .env.template
          sed -i "s/{{PORT}}/1990/g" .env.template
          sed -i "s|{{DB_HOST}}|dropsong-database-dev.cnoepyc88uql.us-east-1.rds.amazonaws.com|g" .env.template
          sed -i "s/{{DB_PORT}}/3306/g" .env.template
          sed -i "s/{{DB_USN}}/${{ secrets.DB_USN_DEV }}/g" .env.template
          sed -i "s/{{DB_PASSWORD}}/${{ secrets.DB_PWD_DEV }}/g" .env.template
          sed -i "s/{{DB_NAME}}/${{ secrets.DB_NAME_DEV }}/g" .env.template
          cp .env.template .env
          cat .env
          cd ../

      - name: "Unit test + Functional test"
        run: yarn test
      
      - name: "E2E install"
        run: |
          yarn e2e-testing install
          yarn e2e-testing install:playwright

      - name: "Start app locally"
        run: |
          yarn dev:server &
          yarn dev:fe &
      
      - name: "E2E run"
        run: yarn e2e-testing test